### ISSUE TITLE
Using InnerHTML when InnerText should be used

### ISSUE THREAD

**Issue by miggs125** [Hansol-Cho/my-note-app#3]
Hi,

I noticed that you use innerHTML in your implementation of the save function in the index.html file. Perhaps innerText might be a better approach if you are trying to save the input as plain text. Also, it is better to let the user know that saving did not occur instead of throwing an error. 

https://stackoverflow.com/questions/19030742/difference-between-innertext-and-innerhtml

```js
          function saveNote() {
                    fs.writeFile('/note', document.querySelector('#note').innerHTML, (err) => {
                        if (err) {
                            throw err;
                        } else {
                            console.log("Note saved!" + document.querySelector("#note").innerHTML);
                        }
                    });
                }
```

I would be happy to work on this issue.

**Comment by Hansol-Cho** [comment]
Interesting! yeah I accept pull request!
