### ISSUE TITLE
New Feature- Adding shortcut for instant save

### ISSUE THREAD

**Issue by Reza-Rajabi** [Hansol-Cho/my-note-app#4]
Hi,

I have noticed that the script for 'hotkeys' feature is included, but it is not implemented. I will try to add this feature to your note-taking app as my Release1.

**Comment by Hansol-Cho** [comment]
Thanks for helping this! Yeah would be awesome if we have some hotkeys!

**Comment by Reza-Rajabi** [comment]
Thank you for accepting the pull request.
