### ISSUE TITLE
Use callback function when saving note

### ISSUE THREAD

**Issue by jacob-shuman** [Hansol-Cho/my-note-app#8]
Currently when saving a note using the ctrl+s hotkey, it attempts to save the note and displays an alert immediately after regardless of the outcome.

I would like to fix this if that's ok with you.

**Comment by Hansol-Cho** [comment]
Sure! Thanks for helping to fix it!

**Comment by jacob-shuman** [comment]
> Sure! Thanks for helping to fix it!

Pull request submitted, thank you for the quick response!
